### ISSUE TITLE
cannot finish install

### ISSUE THREAD

**Issue by chiisaihayashi** [gopher-net/docker-ovs-plugin#20]
Hi,

I have alway met the following error when I start "./docker-ovs-plugin -d"
How could I solve the issue?

vagrant@ovsnode:/home/vagrant# ./docker-ovs-plugin -d
DEBU[0000] socket file [ /usr/share/docker/plugins/ovs.sock ] already exists, deleting..
DEBU[0000] Plugin socket path is [ /usr/share/docker/plugins/ ] with a file handle [ ovs.sock ]
INFO[0000] OVSDB network driver initialized

ovs-plugin is very interesting!!

thx,

**Comment by nerdalert** [comment]
Hiya @chiisaihayashi to get rid of the debug `DEBU[0000]` logs just don't pass the debug `-d` flag like so: `./docker-ovs-plugin`. We put the plugins up from weekend hacking so we could point folks to some references for plugging into Libnetwork so the debug is just to get a closer look at how the proverbial sausage is made and how a plugin interacts with libnetwork :) Thanks.
