### ISSUE TITLE
Provided docker-ovs-plugin triggers 404 from docker engine

### ISSUE THREAD

**Issue by FlorianOtel** [gopher-net/docker-ovs-plugin#26]
Details in this gist:  https://gist.github.com/FlorianOtel/7c2f9ce224963e6d5b38

**Comment by nerdalert** [comment]
Hey @FlorianOtel I added god eps to manage the dependencies. A version of godbus is required that is installed via the libnetwork godeps so we would have missed it. If you get a sec +1 or +1 and merge the patch if it resolves your issue. Apprec!
